apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "module07.fullname" . }}
  labels:
    {{- include "module07.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
automountServiceAccountToken: false
