apiVersion: v1
kind: Service
metadata:
  name: {{ include "module11.fullname" . }}
  labels:
    {{- include "module11.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8011
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: module11-observability
    app.kubernetes.io/instance: {{ .Release.Name }}
